@startuml
class 统计模块 
{
    当前品牌:
    数据文件需要更新标志:
    
}
@enduml


[500,600]
一:初始化/保存:
1.根据品牌倒入文件数据,
2.品牌变化倒入数据

二:需要以一定的频率监控数据的变化.
1.需要的数据:转速,测量时间,重量变化,重量变化/测量时间
2.计算周期:转速不变的持续时间.转速变化,重新计算.
3.记录数据,数据示例:
{
    
    "data":
    {
        "rpm_start": 500,
        [
            // 按照时间先后排序.
            {
                "rpm" : 531,
                "period" : 120,
                "weight" : 0.8, //重量变化越大的占权重越大,因为称重的误差越小.
            },
            {
                "rpm" : 671,
                "period" : 170,
                "weight" : 1.5, 
            }
        ]
    }
}
4.数据更新,每个区间维持在一定数据量.剔除发生时间在前面的

三.根据数据拟合曲线
1.用高阶多项式(三阶/四阶)
2.高斯牛顿
3.线性拟合进行比较